# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='files',
            new_name='file',
        ),
    ]
